config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  resources :jobs, only:[:show, :new, :create]
  resources  :companies, only:[:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @jobs = Job.all
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def show
    @job = Job.find(params[:id])
  end
  
  def new
    @job = Job.new
  end
  
  def create
    @job = Job.create(params.require(:job)
              .permit(:title, :location, :category, :company_id, :description, :featured))
    redirect_to @job 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Emprego Já</h1>

<% @jobs.each do |job|%>
  <h1><%= link_to job.title, job_path(job.id) %></h1>
  <%= job.category %>
  <%= job.company.name %>
  <%= job.location %>
  <% if job.featured? %>
    <strong>Destaque</strong>
  <% end %>
<% end %>

app/views/jobs/new.html.erb
<%= form_for @job do |f| %>
  <%= f.label :title, "Título" %>
  <%= f.text_field :title%>
  <%= f.label :location, "Local" %>
  <%= f.text_field :location %>
  <%= f.label :category, "Categoria" %>
  <%= f.text_field :category %>
  <%= f.collection_select(:company_id, Company.all, :id, :name) %>
  <%= f.label :company_id, "Empresa" %>
  <%= f.label :description, "Descrição" %>
  <%= f.text_field :description %>
  
  <%= f.check_box(:featured) %>
  <%= f.label(:featured, "Destaque") %>
  
  <%= f.submit "Criar Vaga" %>
<% end %>

app/views/jobs/show.html.erb
<h1><%= @job.title %></h1>
<%= @job.location %>
<%= @job.category %>
<%= @job.company.name %>
<%= @job.description %>

<% if @job.featured? %>
  <strong>Destaque</strong>
<% end %>

<%= link_to "Voltar", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Empregojahome1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>